openapi: 3.0.0
info:
  title: Code Improve API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0 
  

servers:
  - url: http://localhost:3000

paths:
  /api/register/user:
    post:
      summary: Create the user
      description: Create a new user in the system.
      tags:
       - UserController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the user.
                email:
                  type: string
                  description: The email of the user.
                password:
                  type: string
                  description: The password of the user
              required:
                - name
                - email
                - password
      responses:
        201:
          description: User created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the user.
    
  /api/login/user:
    post:
      summary: login the user
      description: Authenticate the user .
      tags:
       - UserController
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email of the user.
                password:
                  type: string
                  description: The password of the user
              required:
                - email
                - password
      responses:
        201:
          description: User created successfully.
        400:
          description: Invalid request data.
        500:
          description: An error occurred while creating the user.
        
  
            

        