trigger:
- main  # or the name of your main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'D:\NodeJS Microservice Boilerplate\src\server.ts'  # Specify the path to your TypeScript build output
    artifactName: 'drop'

