trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true

- script: |
    npm install
    npm run custom-build   # Replace 'custom-build' with the actual build script in your package.json
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'D:/Release'
    artifactName: 'drop'
