trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: e2e-server
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
