trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

