trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build -- --project tsconfig.json  # Update the path to your tsconfig.json file
    npm run test
  displayName: 'npm install, build, and test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'  # Use this directory to store the artifact
    artifact: 'my-app-artifact'  # Specify a unique artifact name

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'AwsArtificat'
    sourceFolder: '$(Pipeline.Workspace)/my-app-artifact'
    contents: '**'
    targetFolder: '/var/my-app'
